name: networking_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cuberto_bottom_bar: ^3.1.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  package_info_plus: ^8.1.1
  
  share_plus: ^10.1.2
  flutter_json_view: ^1.1.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
